// Mocks generated by Mockito 5.4.6 from annotations
// in lucy_app/test/socket_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:lucy_app/features/audio_room/service/socket_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocketService extends _i1.Mock implements _i2.SocketService {
  MockSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<Map<String, dynamic>>> get handQueueStream =>
      (super.noSuchMethod(
        Invocation.getter(#handQueueStream),
        returnValue: _i3.Stream<List<Map<String, dynamic>>>.empty(),
      ) as _i3.Stream<List<Map<String, dynamic>>>);

  @override
  _i3.Stream<bool> get connectionStream => (super.noSuchMethod(
        Invocation.getter(#connectionStream),
        returnValue: _i3.Stream<bool>.empty(),
      ) as _i3.Stream<bool>);

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  void connect({
    String? url,
    String? jwtToken,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
          {
            #url: url,
            #jwtToken: jwtToken,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitJoinRoom({
    required String? roomId,
    required String? userId,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #emitJoinRoom,
          [],
          {
            #roomId: roomId,
            #userId: userId,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitLeaveRoom({
    required String? roomId,
    required String? userId,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #emitLeaveRoom,
          [],
          {
            #roomId: roomId,
            #userId: userId,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitRaiseHand({
    required String? roomId,
    required String? userId,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #emitRaiseHand,
          [],
          {
            #roomId: roomId,
            #userId: userId,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitToggleMic({
    required String? roomId,
    required String? userId,
    required bool? isMuted,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #emitToggleMic,
          [],
          {
            #roomId: roomId,
            #userId: userId,
            #isMuted: isMuted,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void disconnect() => super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
