// Mocks generated by Mockito 5.4.6 from annotations
// in lucy_app/test/wallet_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:lucy_app/features/wallet/service/wallet_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWalletBalance_0 extends _i1.SmartFake implements _i2.WalletBalance {
  _FakeWalletBalance_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WalletService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletService extends _i1.Mock implements _i2.WalletService {
  MockWalletService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.WalletBalance> getBalance() => (super.noSuchMethod(
        Invocation.method(
          #getBalance,
          [],
        ),
        returnValue: _i3.Future<_i2.WalletBalance>.value(_FakeWalletBalance_0(
          this,
          Invocation.method(
            #getBalance,
            [],
          ),
        )),
      ) as _i3.Future<_i2.WalletBalance>);

  @override
  _i3.Future<_i2.WalletBalance> deposit({required int? amount}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deposit,
          [],
          {#amount: amount},
        ),
        returnValue: _i3.Future<_i2.WalletBalance>.value(_FakeWalletBalance_0(
          this,
          Invocation.method(
            #deposit,
            [],
            {#amount: amount},
          ),
        )),
      ) as _i3.Future<_i2.WalletBalance>);

  @override
  _i3.Future<void> sendGift({
    required String? toUserId,
    required int? amount,
    required String? giftType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendGift,
          [],
          {
            #toUserId: toUserId,
            #amount: amount,
            #giftType: giftType,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
